### ISSUE TITLE
-pvc or single-shot build and view current location

### ISSUE THREAD

**Issue by yadayadaydadaa** [latex-lsp/texlab-vscode#238]
The documentation (https://texlab.netlify.app/docs/installation/previewing) tells to add `-pvc` to `latexmk` parameters for a continuously refreshing build. I presume this also requires the viewer to continuously refresh (unlike usually done with synctex: most latex toolboxes tell to disable continuous refreshing) as `latexmk` documentation for `-pvc` says nothing about the viewer being relaunched.

However,  _with `-pvc` the build popup dialog newer goes away_; the bar in it keeps scrolling as `latexmk` is constantly running in the background. There should probably be another option to make texlab behave correctly in this case and not show the dialog (rather some indicator in the status bar for `latexmk` being running). 

Why am I trying `-pvc`? I agree that previewing should be a feature of the build system, but also strongly insist that software should _just do the right thing_ instead of requiring assembly of intuitive actions from nuts and bolts (*ahem*, git). I need to be able to press just one key to build and refresh the viewer at the location where the build was triggered. This is the default behaviour of the relevant packages in Sublime Text, and I've forked LaTeX-Workshop to do so as the authors refuse to remove a single line from the code to enable this Most Usable Behaviour: it explicitly checks for a running viewer and prevents refresh if the viewer is already running, but otherwise launches it. Unfortunately  LaTeX-Workshop is just way too bloated and problematic, so I'm trying to get Texlab to work sanely. Thus the recommended `-pvc` combined with only ever doing `save + forward-search` (unfortunately with some delay) could be less painful than sticking with LaTeX-Workshop and trying to maintain my own fork.

Alternatively, would it be possible to pass all the relevant parameters (line number, etc.) to a `latexmk` wrapper that does the forward-search after the build is finished? So basically add `%l` to supported placeholders in `latex.build.args`. I think this would be ideal, unless there's some specific benefits from `-pvc` for the build process (which are tediously long).

**Comment by pfoerster** [comment]
> However, with -pvc the build popup dialog newer goes away; the bar in it keeps scrolling as latexmk is constantly running in the background. There should probably be another option to make texlab behave correctly in this case and not show the dialog (rather some indicator in the status bar for latexmk being running).

With c658e3bf093175ea6800c829e33dd1ad3b39cf37, the extension shows the build status now in the status bar. Clicking on the icon cancels the build. Note that you should not mix `-pvc` and `latex.build.onSave` until we fix detecting duplicate builds in the server, which should be very soon. Once this is done, we will publish a new release. For now, press F5 once at the begin of the editing session and the viewer should reload automatically whenever you save a file. 

> Alternatively, would it be possible to pass all the relevant parameters (line number, etc.) to a latexmk wrapper that does the forward-search after the build is finished? So basically add %l to supported placeholders in latex.build.args. I think this would be ideal, unless there's some specific benefits from -pvc for the build process (which are tediously long).

As you may know, `texlab` implements the language server protocol.
Unfortunately, it is not possible to retrieve the position of the cursor at a given point in time so there is no easy way, `texlab` can know the line number.

**Comment by yadayadaydadaa** [comment]
> As you may know, `texlab` implements the language server protocol.
> Unfortunately, it is not possible to retrieve the position of the cursor at a given point in time so there is no easy way, `texlab` can know the line number.

Why would the part of knowing the cursor position be any more difficult than with the forward search: a key press triggers a function that gathers the relevant information and passes it on. I don't even want the viewer to jump to the position where the cursor is when the build is finished, I want it to jump to the position where the cursor was when the key triggering the build was pressed. This should be known: the forward-search key press hook knows it. 

It shouldn't be too difficult to write a wrapper around the current build routine (after all, something gets triggered once the build is finished to close the notification dialog), and then do the forward-search from VSCode. But I think it would be cleaner/nicer to make the builder do it.

**Comment by yadayadaydadaa** [comment]
Seems to work. Great! Thanks!
