### ISSUE TITLE
"A build error occured." without an error

### ISSUE THREAD

**Issue by ghost** [latex-lsp/texlab-vscode#239]
Frequently I get the message “_A build error occured. Please check the problems tab and the build log for further information_” without any errors to be found in any logs. The document compiles just fine from the command line. Based on time stamps of the log file for the document, the build was never attempted.

**Comment by yadayadaydadaa** [comment]
Right now this problem occurs in all the `.tex` files in one directory, but other directories are fine. I've tried deleting all the temporary files, reloading the VSCode window, etc., but no help.

**Comment by pfoerster** [comment]
`texlab 2.1.0` introduces new logging statements to help debug this issue. You can obtain the logs by cloning the `texlab-vscode` repository and pressing F5 inside VSCode. The log output can be found in the output panel inside the `LaTeX` channel. Please look for an error of the form `Unable to build the document ...`.

**Comment by yadayadaydadaa** [comment]
I still get no logs…

**Comment by yadayadaydadaa** [comment]
It's as if it were executing latexmk in the incorrect directory. The same command from the command line works just fine.

```
Latexmk: This is Latexmk, John Collins, 26 Dec. 2019, version: 4.67.
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex -synctex=1 -interaction=batchmode -shell-escape  -synctex=1 -recorder  "sketches"'
------------
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
Latexmk: fls file doesn't appear to have been made.
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'sketches.log' for details
----------------------
This message may duplicate earlier message.
Latexmk: Failure in processing file '/Users/username/test/sketches.tex':
   (Pdf)LaTeX didn't generate the expected log file 'sketches.log'
----------------------
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
Latexmk: Errors, so I did not complete making targets
```

**Comment by yadayadaydadaa** [comment]
Indeed… it I just open a file from the command line (`code -n sketches.tex`), or if I have not added a directory to the workspace, it fails. After adding a directory to the workspace the builds start succeeding. So it seems it's not changing to the directory of the _file_ but to the workspace (which may be empty).

**Comment by yadayadaydadaa** [comment]
The same error occurs if the workspace has several associated directories.

**Comment by pfoerster** [comment]
Can you try setting `latex.rootDirectory` to `null`, please?

**Comment by yadayadaydadaa** [comment]
Yes, that seems to fix it.
