### ISSUE TITLE
Document use with Tectonic

### ISSUE THREAD

**Issue by LiHRaM** [latex-lsp/texlab-vscode#242]
Hey, loving this extension. I just figured out how to get it working with [`tectonic`](https://tectonic-typesetting.github.io/), a Rust tool for building LaTeX documents.

I think it would be useful to document how to do this so that users can quickly get started if they want to use a `latexmk` alternative. Anyway, here's the .vscode setup:

```jsonc
{
    // Settings for TeXLab (efoerster.texlab)
    // See `tectonic --help` for the format
    "latex.build.executable": "tectonic",
    "latex.build.args": [
        // Input
        "%f",
        // Flags
        "--synctex",
        "--keep-logs",
        "--keep-intermediates",
        // Options
        // OPTIONAL: If you want a custom out directory,
        // uncomment the following line.
        //"--outdir out",
    ],
    // OPTIONAL: The extension needs to be configured 
    // to read the logs from the out directory as well.
    // "latex.build.outputDirectory": "out",
}
```

Would you be open to a merge request that updates the README or some documentation with this example?

**Comment by pfoerster** [comment]
> Would you be open to a merge request that updates the README or some documentation with this example?

Of course. You can put it on our [website](https://github.com/latex-lsp/texlab-web). I think the best place would be the "Getting Started" section.
Thank you for contributing.

> Hey, loving this extension.

Thanks! I am glad you like it.

**Comment by LiHRaM** [comment]
Thanks. I'll close this issue!
