### ISSUE TITLE
incomplete aux files

### ISSUE THREAD

**Issue by ghost** [latex-lsp/texlab-vscode#250]
I started getting a weird error on some files (at least two, while one is ok): when I compile the document through texlab, the aux-file is incomplete, simply ends in the middle of a line, and the compilation fails:
```
File ended while scanning use of \@writefile.
```
Running `latexmk` from the command line, there is no problem (needs two runs two first fix the broken aux-file).  There are no errors reported. Trying to rebuild through texlab consistently again breaks the aux-file.

**Comment by pfoerster** [comment]
Fixed by https://github.com/latex-lsp/texlab/issues/372#issuecomment-843281588
