### ISSUE TITLE
2.2.0: unable to start server

### ISSUE THREAD

**Issue by yadayadaydadaa** [latex-lsp/texlab-vscode#255]
Since updating to 2.2.0, there's an error either downloading or starting the server. I have auto-download enabled (how to you download the server without auto-download?). It does not complain about that, but afterwards fails to start the server:
```
[Error - 09:44:05] Starting client failed
Launching server using command /Users/username/.vscode/extensions/efoerster.texlab-2.2.0/server/texlab
```
No such file exists. However `efoerster.texlab-2.2.0/server/target/release/texlab` does exist.

**Comment by yadayadaydadaa** [comment]
As a workaround one can create a symlink from the expected location to `target/release/texlab`. This seems to be the correct version as it fixes https://github.com/latex-lsp/texlab/issues/228.

**Comment by efoerster** [comment]
This should be fixed now. The release artifacts were not archived correctly.

**Comment by yadayadaydadaa** [comment]
Yes, fixed. Thanks!
