### ISSUE TITLE
Auto-closing paired quotes

### ISSUE THREAD

**Issue by coxackie** [latex-lsp/texlab-vscode#390]
May I suggest that
```
["`", "'"]
```
ia added in both `"autoClosingPairs":` and `"surroundingPairs":` of `latex.json`? One often needs to insert latex-style quotes, and this would be very helpful.

**Comment by pfoerster** [comment]
Thanks for the suggestion. This feature has shipped with `texlab 3.0.0` (and upwards).

**Comment by coxackie** [comment]
thanks - closing
