### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by ghost** [latex-lsp/texlab-vscode#403]
If I run `latexmk -pdf <file.tex>` from the command line, the project successfully get built. 

If I try the smae thing, but running with the extension, I get: 

```
[...]
!pdfTeX error: pdflatex.exe (file c:/Users/phg/AppData/Roaming/texlive/2020/tex
mf-dist/fonts/type1/public/amsfonts/cm/cmss10.pfb): fflush() failed (Invalid ar
gument)
 ==> Fatal error occurred, no output PDF file produced!
```

**Comment by phgmacedo** [comment]
Settings are: 
```
    "latex.build.args": [
        "-pdf",
        "main.tex"
    ],
    "latex.build.executable": "latexmk",
    "latex.rootDirectory": null
```

**Comment by phgmacedo** [comment]
Ideally, I would like to set the build command to just execute `make` on the folder.

**Comment by pfoerster** [comment]
Fixed with https://github.com/latex-lsp/texlab/commit/3176540d7d9776d9aaf6c5a2c09bc0342a2ed64a
