### ISSUE TITLE
VSCode extension broken after texlab server update

### ISSUE THREAD

**Issue by coxackie** [latex-lsp/texlab-vscode#425]
I am using the VSCode extension with the local texlab server, and after the update to 3.0.0, the extension crashes. I guess this is to be expected; I will downgrade for the time being, but it will be nice to have the extension play nicely with the latest server.

**Comment by pfoerster** [comment]
> I am using the VSCode extension with the local texlab server, and after the update to 3.0.0, the extension crashes. I guess this is to be expected; I will downgrade for the time being, but it will be nice to have the extension play nicely with the latest server.

Thanks for the report. The code for the extension has already been updated but it is not published yet. Once @efoerster has updated the personal access token, I will trigger a release.

**Comment by coxackie** [comment]
Thanks - it works now. I am having a bit of issue with log parsing (I think), but I will open another issue for this. Feel free to close.
