### ISSUE TITLE
autoClosingPairs for \left \right

### ISSUE THREAD

**Issue by coxackie** [latex-lsp/texlab-vscode#478]
Please consider adding the following to the `autoClosingPairs` part of `latex.json`:
```
    ["\\left\\{", "\\right\\}"],
    ["\\left[", "\\right]"],
    ["\\left(", "\\right)"],
```
Too often I type `\left` and would like to autoclose. I am not sure this is the best solution - if there would be a way to "abstract" the inclusion of `\right` for any `\left` it would be great. Of course, this could be achieved with snippets, but the extension does not offer those...

**Comment by pfoerster** [comment]
Thanks for the suggestion 👍 .

> Of course, this could be achieved with snippets, but the extension does not offer those...

Actually, `texlab` does have one snippet (the `begin` snippet), which is provided by the server. I think we can add another set of snippets to the server so other editors can benefit as well. This should be straight-forward so you can expect this feature soon.

**Comment by pfoerster** [comment]
Sorry for the long delay. The new version with the additional auto closing pairs has now been published.
