### ISSUE TITLE
Using vscode-LaTeX-support to highlight syntax

### ISSUE THREAD

**Issue by torn4dom4n** [latex-lsp/texlab-vscode#497]
I own [vscode-LaTeX-support](https://marketplace.visualstudio.com/items?itemName=torn4dom4n.latex-support). In my view, I can add my extension to support LaTeX grammar in this extension. It maybe fix #478.
Thanks.

**Comment by pfoerster** [comment]
Thanks for the suggestion. I tried out your extension and it seems to be working quite nicely together with `texlab`. In particular, it fixes #478. I think it might make sense to add an extension dependency to `texlab-vscode` so it installs your extension as well. What do you think?

**Comment by torn4dom4n** [comment]
> Thanks for the suggestion. I tried out your extension and it seems to be working quite nicely together with `texlab`. In particular, it fixes #478. I think it might make sense to add an extension dependency to `texlab-vscode` so it installs your extension as well. What do you think?

I agree with you. Let's try that.

**Comment by coxackie** [comment]
Does this mean that all grammar and highlighting will be done through `vscode-LaTeX-support`? I am asking because I once used [latex-syntax](https://marketplace.visualstudio.com/items?itemName=vomout.latex-syntax) together with `texlab-vscode` (it is actually the "recommended" use of `latex-syntax`), but I found there were sometimes overrides in grammar, as it was defined in both extensions (I cannot recall exactly what, but it led me to removing `latex-syntax` eventually.)

**Comment by septatrix** [comment]
A while ago I read an issue in the Latex-Workshop repo referencing [this comment](https://github.com/James-Yu/LaTeX-Workshop/commit/8dfaeb2cc314872293546fa453de352940b88bea#commitcomment-51335775) from @aeschli that the vscode team would be willing to bundle a basic latex extension in vscode itself. Currently there seem to be multiple extensions providing grammars/highlighting and if this could be reduced to a single built-in one that would simplify things for many LaTeX extensions

**Comment by coxackie** [comment]
This is very interesting - in fact, it went further ahead: read https://github.com/James-Yu/LaTeX-Workshop/issues/2731.

 If the VSCode team decides to have grammar/highlighting, the the present extension can simply focus on talking to Texlab, and keep it sweet and simple.

**Comment by jlelong** [comment]
Hi, I am a PM at [James-Yu/LaTeX-Workshop](https://github.com/James-Yu/LaTeX-Workshop). As you pointed out, the VS Code team has decided to provide built-in support for the LaTeX grammar.  We have outsourced our LaTeX grammar from LaTeX-Workshop to https://github.com/jlelong/vscode-latex-basics and the VS Code team will regularly be pulling updates. The LaTeX support is already available in the latest insider version and will be in the January 2022 release.

**Comment by torn4dom4n** [comment]
> Hi, I am a PM at [James-Yu/LaTeX-Workshop](https://github.com/James-Yu/LaTeX-Workshop). As you pointed out, the VS Code team has decided to provide built-in support for the LaTeX grammar. We have outsourced our LaTeX grammar from LaTeX-Workshop to https://github.com/jlelong/vscode-latex-basics and the VS Code team will regularly be pulling updates. The LaTeX support is already available in the latest insider version and will be in the January 2022 release.

This is a better solution so I'll close this issue.
