### ISSUE TITLE
Lazily load extension after opening tex files

### ISSUE THREAD

**Issue by septatrix** [latex-lsp/texlab-vscode#523]
I noticed that the texlab extension loads on startup even if not tex files have been opened yet.
Code should allow to load extensions only once a corresponding file has been opened.
If that is possible to use with the language server than that would increase startup time for all users in case they are not working on tex.

![image](https://user-images.githubusercontent.com/24257556/132053738-f939c43f-2722-413f-8981-751ac24078d9.png)

**Comment by pfoerster** [comment]
Sorry for the late response. e3b82819603d24c31f7d73ec7b1e854a4260ac7b fixes the issue.

I will publish a new release tomorrow.

**Comment by pfoerster** [comment]
Fixed with the 3.3.2 release of the extension.
