### ISSUE TITLE
Custom command not detected

### ISSUE THREAD

**Issue by mw88-personal** [latex-lsp/texlab-vscode#618]
I'm having some unexpected behaviour with this code:

        \documentclass{article}

        \newcommand\firsttest[1][defaultONE]{%
            \textbf{#1}%
        }%
        \newcommand{\secondtest}[1][defaultTWO]{%
            \texttt{#1}
        }%

        \begin{document}
            \firsttest[firsttest]
            \secondtest[secondtest]
        \end{document}

It defines two new commands, with one optional argument each, and uses them in the document. Notice, the only difference is, that in ``\firsttest`` the macro name is not wrapped in braces. In the definition of the second macro, the macro name is wrapped in braces, which is the documented LaTeX way to do it.

I expect the following behaviour using texlab-vscode:
* Intellisense suggesting completion of ``firsttest`` when typing ``\firs``
* Intellisense suggesting completion of ``secondtest``, when typing ``\seco``

Instead, the observed behaviour is:
* completion to ``\firsttest`` works as expected
* no Intellisense suggestion for ``\secondtest``.

I specifically ensured, that the document was saved after the definitions and before trying autocompletion in the document environment.
I think, that not recognizing the second definition is a bug.

**Comment by pfoerster** [comment]
Thanks for the report. This is a bug in the `texlab` server, which has been fixed with https://github.com/latex-lsp/texlab/commit/470aa8592e852fe1141de3436d1e48b8257ef6f4.

I will publish a new patch release along with other fixes tomorrow.
