### ISSUE TITLE
OpenVSX: No pre-built binaries available for your platform

### ISSUE THREAD

**Issue by yashpalgoyal1304** [latex-lsp/texlab-vscode#820]
No pre-built binaries available for your platform. Please install the server manually. For more information, see https://github.com/latex-lsp/texlab.

Environment & Versions:
* editor: vscodium: 1.71.2 (system setup)
* extension link: https://open-vsx.org/vscode/item?itemName=efoerster.texlab
* windows: 10 20H2
* tex distribution: miktex

**Comment by pfoerster** [comment]
> Ok, I guess I figured that it has to be somewhere where it can be found using the PATH variable. Could you provide a configuration option for a custom path?

Sure, the next version will include a `texlab.server.path` setting 👍. Once, we are verified on `Open VSX`, we can publish the extension with binaries as well.

**Comment by yashpalgoyal1304** [comment]
per the microsoft lsp page, kate supports LSP. so, does the texlab server work with kate editor?

https://microsoft.github.io/language-server-protocol/implementors/tools/

**Comment by yashpalgoyal1304** [comment]
> Once, we are verified on `Open VSX`, we can publish the extension with binaries as well.

umh, the VSX page for the extension shows the "verified publisher" badge. is there some other verification you are talking about?


![Uploading image.png…]()

**Comment by pfoerster** [comment]
> per the microsoft lsp page, kate supports LSP. so, does the texlab server work with kate editor?

Sure, there is even a blog post with an example configuration on the Kate website:
https://kate-editor.org/post/2019/2019-08-10-kate-lsp-more-languages-supported/

> umh, the VSX page for the extension shows the "verified publisher" badge. is there some other verification you are talking about?

Yeah, we need to receive the publishing rights for the extension first (see here: https://github.com/EclipseFdn/open-vsx.org/issues/1518). At the moment, the extension was auto-published by `open-vsx`. Then, we can publish a version with the server binary ;)

**Comment by pfoerster** [comment]
@yashpalgoyal1304 `texlab` is now available on `Open VSX`: https://open-vsx.org/extension/efoerster/texlab

**Comment by yashpalgoyal1304** [comment]
thanks
